/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.5 */

#include "my-proto.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(MyProtoItem1, MyProtoItem1, AUTO)


PB_BIND(MyProtoSubItem, MyProtoSubItem, AUTO)


PB_BIND(MyProtoItem2, MyProtoItem2, AUTO)


PB_BIND(MyProtoRequest, MyProtoRequest, AUTO)




