/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.5 */

#ifndef PB_MY_PROTO_PB_H_INCLUDED
#define PB_MY_PROTO_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _MyProtoEnum { 
    MyProtoEnum_MPE_NOT_SET = 0, 
    MyProtoEnum_MPE_OPTION_1 = 1, 
    MyProtoEnum_MPE_OPTION_2 = 2 
} MyProtoEnum;

/* Struct definitions */
typedef struct _MyProtoItem1 { 
    char name[32]; 
    uint32_t commandId; 
    pb_byte_t colorRgbBytes[3]; 
} MyProtoItem1;

typedef struct _MyProtoSubItem { 
    char value[10]; 
} MyProtoSubItem;

typedef struct _MyProtoItem2 { 
    pb_callback_t item1; 
    bool has_subItem;
    MyProtoSubItem subItem; 
} MyProtoItem2;

typedef struct _MyProtoRequest { 
    pb_size_t which_request;
    union {
        MyProtoItem1 myProtoItem1;
        MyProtoItem2 myProtoItem2;
    } request; 
} MyProtoRequest;


/* Helper constants for enums */
#define _MyProtoEnum_MIN MyProtoEnum_MPE_NOT_SET
#define _MyProtoEnum_MAX MyProtoEnum_MPE_OPTION_2
#define _MyProtoEnum_ARRAYSIZE ((MyProtoEnum)(MyProtoEnum_MPE_OPTION_2+1))


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define MyProtoItem1_init_default                {"", 0, {0}}
#define MyProtoSubItem_init_default              {""}
#define MyProtoItem2_init_default                {{{NULL}, NULL}, false, MyProtoSubItem_init_default}
#define MyProtoRequest_init_default              {0, {MyProtoItem1_init_default}}
#define MyProtoItem1_init_zero                   {"", 0, {0}}
#define MyProtoSubItem_init_zero                 {""}
#define MyProtoItem2_init_zero                   {{{NULL}, NULL}, false, MyProtoSubItem_init_zero}
#define MyProtoRequest_init_zero                 {0, {MyProtoItem1_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define MyProtoItem1_name_tag                    1
#define MyProtoItem1_commandId_tag               2
#define MyProtoItem1_colorRgbBytes_tag           3
#define MyProtoSubItem_value_tag                 1
#define MyProtoItem2_item1_tag                   1
#define MyProtoItem2_subItem_tag                 2
#define MyProtoRequest_myProtoItem1_tag          1
#define MyProtoRequest_myProtoItem2_tag          2

/* Struct field encoding specification for nanopb */
#define MyProtoItem1_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   name,              1) \
X(a, STATIC,   SINGULAR, UINT32,   commandId,         2) \
X(a, STATIC,   SINGULAR, FIXED_LENGTH_BYTES, colorRgbBytes,     3)
#define MyProtoItem1_CALLBACK NULL
#define MyProtoItem1_DEFAULT NULL

#define MyProtoSubItem_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   value,             1)
#define MyProtoSubItem_CALLBACK NULL
#define MyProtoSubItem_DEFAULT NULL

#define MyProtoItem2_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   item1,             1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  subItem,           2)
#define MyProtoItem2_CALLBACK pb_default_field_callback
#define MyProtoItem2_DEFAULT NULL
#define MyProtoItem2_subItem_MSGTYPE MyProtoSubItem

#define MyProtoRequest_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request,myProtoItem1,request.myProtoItem1),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request,myProtoItem2,request.myProtoItem2),   2)
#define MyProtoRequest_CALLBACK NULL
#define MyProtoRequest_DEFAULT NULL
#define MyProtoRequest_request_myProtoItem1_MSGTYPE MyProtoItem1
#define MyProtoRequest_request_myProtoItem2_MSGTYPE MyProtoItem2

extern const pb_msgdesc_t MyProtoItem1_msg;
extern const pb_msgdesc_t MyProtoSubItem_msg;
extern const pb_msgdesc_t MyProtoItem2_msg;
extern const pb_msgdesc_t MyProtoRequest_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define MyProtoItem1_fields &MyProtoItem1_msg
#define MyProtoSubItem_fields &MyProtoSubItem_msg
#define MyProtoItem2_fields &MyProtoItem2_msg
#define MyProtoRequest_fields &MyProtoRequest_msg

/* Maximum encoded size of messages (where known) */
/* MyProtoItem2_size depends on runtime parameters */
/* MyProtoRequest_size depends on runtime parameters */
#define MyProtoItem1_size                        44
#define MyProtoSubItem_size                      11

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
